"""
risk_analysis_export.py
Extended Risk Analysis panel (beta, downside risk, best/worst day, gauges)
and Export Reports (CSV + PDF summary + note on chart image export).

Import:
    from risk_analysis_export import render_extended_risk_analysis, render_export_section
"""

import io
import pandas as pd
import streamlit as st

try:
    from fpdf import FPDF
    _FPDF_AVAILABLE = True
except ImportError:
    _FPDF_AVAILABLE = False


# --------------------------------------------------------------------------
# 1. EXTENDED RISK ANALYSIS
# --------------------------------------------------------------------------

def render_extended_risk_analysis(result: dict):
    st.subheader("Risk Analysis")

    risk = result["risk"]
    ext = result["extended_risk"]

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Daily Volatility", f"{ext['daily_volatility_pct']}%")
    c2.metric("Annualized Volatility", f"{risk['volatility_annualized']}%")
    c3.metric("Max Drawdown", f"{risk['max_drawdown_pct']}%")
    c4.metric("Beta", ext["beta"] if ext["beta"] is not None else "N/A")

    c5, c6 = st.columns(2)
    c5.metric("Downside Risk (Ann.)", f"{ext['downside_risk_pct']}%")
    c6.metric("RSI (14)", risk["rsi"])

    c7, c8 = st.columns(2)
    c7.metric("Best Single Day", f"{ext['best_day_pct']:+.2f}%")
    c8.metric("Worst Single Day", f"{ext['worst_day_pct']:+.2f}%")

    idx = risk["risk_index"]
    if idx < 35:
        st.success(f"Overall Risk Index: {idx}/100 — Low")
    elif idx < 70:
        st.warning(f"Overall Risk Index: {idx}/100 — Moderate")
    else:
        st.error(f"Overall Risk Index: {idx}/100 — High")


# --------------------------------------------------------------------------
# 2. EXPORT REPORTS
# --------------------------------------------------------------------------

def _build_csv(hist: pd.DataFrame) -> bytes:
    return hist.to_csv().encode("utf-8")


def _pdf_safe(text) -> str:
    """Strip characters the default PDF font (Latin-1 only) can't render,
    so unusual company names, dashes, or currency symbols never crash export."""
    return str(text).encode("latin-1", "replace").decode("latin-1")


def _build_pdf_summary(result: dict) -> bytes:
    """Build a simple one-page PDF summary. Requires fpdf2.
    Uses the currency code (e.g. 'INR', 'USD') rather than the currency
    symbol, since the default PDF font doesn't support symbols like ₹."""
    currency_label = result.get("currency", "")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.multi_cell(0, 10, _pdf_safe(f"{result['company_name']} ({result['ticker']})"))

    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 8, _pdf_safe(f"Last Price: {result['last_price']} {currency_label}"))
    pdf.multi_cell(0, 8, _pdf_safe(f"Exchange: {result.get('exchange', 'N/A')}"))
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 13)
    pdf.multi_cell(0, 8, "Signal & Risk")
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 8, _pdf_safe(f"Decision: {result['signal']['decision']}"))
    pdf.multi_cell(0, 8, _pdf_safe(f"Risk Index: {result['risk']['risk_index']} / 100"))
    pdf.multi_cell(0, 8, _pdf_safe(f"Annualized Volatility: {result['risk']['volatility_annualized']}%"))
    pdf.multi_cell(0, 8, _pdf_safe(f"Max Drawdown: {result['risk']['max_drawdown_pct']}%"))
    pdf.multi_cell(0, 8, _pdf_safe(f"RSI: {result['risk']['rsi']}"))
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 13)
    pdf.multi_cell(0, 8, "Reasoning")
    pdf.set_font("Helvetica", "", 11)
    for reason in result["signal"]["reasons"]:
        pdf.multi_cell(0, 7, _pdf_safe(f"- {reason}"))

    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 9)
    pdf.multi_cell(0, 6, "This report is generated by an automated rule-based tool for educational "
                          "purposes only and does not constitute financial advice.")

    return bytes(pdf.output())


def render_export_section(result: dict):
    st.subheader("Export Reports")

    col1, col2 = st.columns(2)
    with col1:
        csv_bytes = _build_csv(result["history"])
        st.download_button(
            "Download Price History (CSV)",
            data=csv_bytes,
            file_name=f"{result['ticker']}_history.csv",
            mime="text/csv",
        )
    with col2:
        if _FPDF_AVAILABLE:
            try:
                pdf_bytes = _build_pdf_summary(result)
                st.download_button(
                    "Download Summary Report (PDF)",
                    data=pdf_bytes,
                    file_name=f"{result['ticker']}_summary.pdf",
                    mime="application/pdf",
                )
            except Exception as e:
                st.caption(f"PDF export unavailable: {e}")
        else:
            st.caption("Install `fpdf2` (`pip install fpdf2`) to enable PDF export.")

    st.caption(
        "To save the price chart as an image, use the camera icon in the "
        "chart's toolbar (top-right of the chart on hover)."
    )
